<template>
  <div class="consent-text text-sm">
    <h2>Introduction</h2>
    <p>
      Thank you for your interest in participating in this research project. The following few
      pages will provide you with further information about the project, so that you can decide
      if you would like to take part in this research.
    </p>
    <p>
      Please take the time to read this information carefully. You may ask questions about
      anything you don't understand or want to know more about.
    </p>
    <p>
      Your participation is voluntary. If you don't wish to take part, you don't have to. If you
      begin participating, you can also stop at any time.
    </p>

    <h2>What is this research about?</h2>
    <p>
      We want to understand the ways that young people's song choices are shaped by music
      recommendations made by music streaming platforms like Spotify. To do this, we need to
      develop systems for collecting data that are clean and useful. In this feasibility study, we
      will try to develop these systems by analysing your music listening history on Spotify and
      then providing you with an accessible and detailed overview of your data for discussion and
      feedback. We are interested to know how closely this information matches your 'Wrapped',
      whether it matches your expectations about your own listening habits, and whether it is
      possible to identify what song choices you made versus whether there were instances of the
      algorithm unknowingly influencing your choices. You will be able to keep your 'Spotify
      Wrapped Unpacked' data.
    </p>

    <h2>What will I be asked to do?</h2>
    <p>
      Should you agree to participate you will request your extended listening history from
      Spotify (we will provide instructions for the latest process) and share the files with the
      researchers. Our team will then analyse and extract information about song frequency,
      duration, time of day, and where possible, the mechanism of choice and create a personalised
      report for your perusal. This 'Spotify Wrapped Unpacked' analysis will be used as the basis
      for discussion with you in a short audio-recorded Zoom interview with one of the researchers.
      We will talk about influences on your listening that you are aware of and that can be
      discerned from the data. This interview will take approximately 45 minutes. Your interview
      will be transcribed using Zoom's automatic transcription service.
    </p>

    <h2>What are the possible benefits?</h2>
    <p>
      You will gain a deeper understanding of your listening habits and get to keep your 'Spotify
      Wrapped Unpacked' report generated by the researchers. Your contribution will inform the
      development of scalable processes that will lead to larger data collection and analysis.
      Further, this information will be used to inform policy and product development with the
      goal of supporting ethical AI recommender systems.
    </p>

    <h2>What are the possible risks?</h2>
    <p>
      Spotify changes their data access regularly and this may lead to delays or the need for
      revisions. This could take time and may be frustrating when you want to get your 'Unpacked'
      package.
    </p>

    <h2>Do I have to take part?</h2>
    <p>
      No. Participation is completely voluntary. There will be a time-lag between you requesting
      your data from Spotify and receiving it via email, which will give you the opportunity to
      decide if you want to share it for the research. You can withdraw at that point. After you
      have donated your data, it will be difficult to change the system that has been built as
      though you had not been involved, but we can double delete all remnants of your data so that
      we cannot use it in ongoing developments from that point.
    </p>

    <h2>Will I hear about the results of this project?</h2>
    <p>
      Yes, we will publish the results of this study in academic research publications and
      presentations. Please let us know if you would like us to send through a summary of what we
      have learned to your email address once the project is completed.
    </p>
  </div>
</template>

<style scoped>
.consent-text > :first-child {
  margin-top: 0;
}
.consent-text h2 {
  font-weight: 600;
  margin-top: 1rem;
  margin-bottom: 0.5rem;
}
.consent-text p {
  margin-bottom: 0.5rem;
}
.consent-text ul,
.consent-text ol {
  margin-bottom: 0.5rem;
  padding-left: 1.25rem;
}
.consent-text li {
  margin-bottom: 0.25rem;
}
</style>
