import { ref } from 'vue'

/**
 * Composable for loading and managing research audit summaries.
 * Audit summaries are generated by Python scripts and provide the 
 * high-level behavioral profiling data for a given subject.
 */

export type BehavioralProfile = {
  skip_rate: number;
  shuffle_rate: number;
  active_selection_score: number;
  
  skip_level: "Low" | "Medium" | "High" | "Unknown";
  shuffle_level: "Low" | "Medium" | "High" | "Unknown";
  deliberate_level: "Low" | "Medium" | "High" | "Unknown";
  
  platform_distribution: Record<string, number>;
  platform_mode: string;
  
  behavioral_label_primary: "Receptive (Provisional)" | "Responsive (Provisional)" | "Deliberate (Provisional)" | "Mixed (Provisional)" | "Insufficient Data";
  classification_confidence: "High" | "Medium" | "Low" | "Baseline" | "None";
  behavioral_basis_note: string;
}

export type AuditSummary = {
  dataset_shape: Record<string, number>;
  date_coverage: Record<string, string>;
  behavioral_profile?: BehavioralProfile;
  routine_heatmap?: Record<string, Record<string, number>>;
  source_composition?: Record<string, number>;
  [key: string]: any;
}

export function useAuditSummary() {
  const summary = ref<AuditSummary | null>(null)
  const loading = ref(false)
  const error = ref<string | null>(null)

  async function loadSummary(subjectId: string) {
    loading.value = true
    error.value = null
    try {
      const res = await fetch(`/data/audit_summary_${subjectId}.json`)
      if (!res.ok) throw new Error('Failed to load audit summary')
      summary.value = await res.json()
    } catch (e: any) {
      error.value = e.message
    } finally {
      loading.value = false
    }
  }

  return { summary, loading, error, loadSummary }
}
